version: "3.9"

services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./configs/custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=password
