#!/bin/bash

echo "Add data to Redis"

ttl=60

host="$(docker inspect -f \
        '{{(index .NetworkSettings.Networks "redis-task_redis-cluster").IPAddress}}' \
        "redis_1")";

for ind in `seq 1 15`; do
    keyWithoutTtl="key_without_ttl_$ind"
    valueWithoutTtl="value_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttlvalue_without_ttl"

    keyWithTtl="key_with_ttl_$ind"
    valueWithTtl="value_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttlvalue_with_ttl"

    commandWithoutTtl="redis-cli -c -h $host -p 6379 SET $keyWithoutTtl \"$valueWithoutTtl\""
    res1=$(docker exec -it redis-cli $commandWithoutTtl)
    echo "$keyWithoutTtl => $res1"

    commandWithTtl="redis-cli -c -h $host -p 6379 SET $keyWithTtl \"$valueWithTtl\" EX $ttl"
    res2=$(docker exec -it redis-cli $commandWithTtl)
    echo "$keyWithTtl - $ttl => $res2"
done
