version: "3.7"

services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./configs/custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf
      - ./logs/mysql/slow-queries.log:/var/log/mysql/slow-queries.log
    environment:
      - MYSQL_ROOT_PASSWORD=password

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    ports:
      - 5601:5601
    links: ['elasticsearch']
    depends_on: ['elasticsearch']
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeat
    links: ['elasticsearch', 'mysql', 'kibana']
    depends_on: ['elasticsearch', 'mysql', 'kibana']
    restart: always
    volumes:
      - ./configs/mysql.yml:/usr/share/filebeat/modules.d/mysql.yml
      # mount the image for reading logs from mysql
      - ./logs/mysql/:/var/log/mysql/
    environment:
      - setup.kibana.host=http://kibana:5601
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
