version: "3.9"

services:
  postgres-sa:
    image: postgres:14.1-alpine
    container_name: postgres-sa
    restart: always
    volumes:
      - ./scripts/pg_stand_alone.sql:/tmp/pg_stand_alone.sql
    environment:
      POSTGRES_PASSWORD: password

  postgres-b:
    image: postgres:14.1-alpine
    container_name: postgres-b
    restart: always
    volumes:
      - ./scripts/pg_b.sql:/tmp/pg_b.sql
    environment:
      POSTGRES_PASSWORD: password
  postgres-b1:
    image: postgres:14.1-alpine
    container_name: postgres-b1
    restart: always
    volumes:
      - ./scripts/pg_b1.sql:/tmp/pg_b1.sql
    environment:
      POSTGRES_PASSWORD: password
  postgres-b2:
    image: postgres:14.1-alpine
    container_name: postgres-b2
    restart: always
    volumes:
      - ./scripts/pg_b2.sql:/tmp/pg_b2.sql
    environment:
      POSTGRES_PASSWORD: password

