version: "3.9"

services:
  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    ports:
      - 11300:11300
  
  redis_aof:
    image: redis:6.2.6
    container_name: redis_aof
    ports:
      - 7001:6379
    volumes:
      - ./redis-aof.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis_rdb:
    image: redis:6.2.6
    container_name: redis_rdb
    ports:
      - 7002:6379
    volumes:
      - ./redis-rdb.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
