version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx-configs/Dockerfile
    container_name: nginx
    volumes:
      - ./nginx-configs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-configs/purge.lua:/var/lib/nginx/lua/purge.lua
      - ./nginx-configs/html:/usr/share/nginx/html
      - ./nginx-configs/cache:/tmp/nginx/cache
    ports:
      - 8080:80
