version: "3.9"

services:
  percona:
    image: percona:8.0
    container_name: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
