spring:
    redis:
        host: redis
        port: 6379
        time-to-live: 5m
        chace-names: customers

    datasource:
        url: jdbc:postgresql://postgresql:5432/postgres
        username: postgres
        password: password
    jpa:
        generate-ddl: true
    hibernate:
        ddl-auto: create

logging:
  level:
    com.prjctr.hsa: DEBUG
 